<div class="inline-flex gap-1">
    <span class="flex w-3 h-3 me-3 bg-sky-700 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-600 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-500 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-400 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-300 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-200 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-100 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-50 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-100 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-200 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-300 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-400 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-500 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-600 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-sky-700 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-gradient-to-r from-sky-700 to-teal-700 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-700 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-600 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-500 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-400 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-300 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-200 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-100 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-50 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-100 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-200 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-300 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-400 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-500 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-600 rounded-full"></span>
    <span class="flex w-3 h-3 me-3 bg-teal-700 rounded-full"></span>
</div>
